# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae3f9dfd07fed53151e0cd840cbd4141c626f30a2dcfdab2d2d5523afa6a7b0370bf52a838674a162097bf72aef5fe1835b7f62230156d21eca02d3c8123e781

test:
  secret_key_base: afcedecb7e39331e4039fe881576e835d01aeb96963f4745d6b1ff9a91c9667b99f83aeec9516b114a5c4cd2ff074e4b483b03b4bdda9b448b76428982cfda18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
